"""add_global_assets_and_text_overlay

Revision ID: 07c4c10b7600
Revises: a1b2c3d4e5f6
Create Date: 2026-02-17 18:53:49.188838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c4c10b7600'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso4_global_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_key')
    )
    op.drop_table('alembic_version')
    with op.batch_alter_table('proceso4_scene_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_overlay', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso4_scene_media', schema=None) as batch_op:
        batch_op.drop_column('text_overlay')

    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('proceso4_global_assets')
    # ### end Alembic commands ###
