"""refactor models endpoints proceso1

Revision ID: 0eeadbc6e979
Revises: 77dd98c30d46
Create Date: 2026-02-15 21:41:53.693349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eeadbc6e979'
down_revision = '77dd98c30d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso1_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proceso1_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proceso1_jobs_video_id'), ['video_id'], unique=False)

    op.create_table('proceso1_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_index', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['proceso1_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source_index', name='uq_proceso1_source_job_index')
    )
    with op.batch_alter_table('proceso1_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proceso1_sources_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso1_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proceso1_sources_job_id'))

    op.drop_table('proceso1_sources')
    with op.batch_alter_table('proceso1_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proceso1_jobs_video_id'))

    op.drop_table('proceso1_jobs')
    # ### end Alembic commands ###
