"""add proceso1 subprocess states

Revision ID: 35809d6d6633
Revises: 0eeadbc6e979
Create Date: 2026-02-15 22:00:53.916343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35809d6d6633'
down_revision = '0eeadbc6e979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso1_subprocess_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('subprocess_key', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['proceso1_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'subprocess_key', name='uq_proceso1_job_subprocess_key')
    )
    with op.batch_alter_table('proceso1_subprocess_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proceso1_subprocess_states_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso1_subprocess_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proceso1_subprocess_states_job_id'))

    op.drop_table('proceso1_subprocess_states')
    # ### end Alembic commands ###
