"""add proceso2_corto tables

Revision ID: 529368b8f119
Revises: d1e2f3a4b5c6
Create Date: 2026-03-14 17:13:58.399234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '529368b8f119'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso2_corto_jobs',
    sa.Column('proceso1_corto_job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proceso1_corto_job_id'], ['proceso1_corto_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proceso1_corto_job_id')
    )
    op.create_table('proceso2_corto_subprocess_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso1_corto_job_id', sa.Integer(), nullable=False),
    sa.Column('subprocess_key', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proceso1_corto_job_id'], ['proceso1_corto_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proceso1_corto_job_id', 'subprocess_key', name='uq_proceso2_corto_job_subprocess_key')
    )
    with op.batch_alter_table('proceso2_corto_subprocess_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proceso2_corto_subprocess_states_proceso1_corto_job_id'), ['proceso1_corto_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso2_corto_subprocess_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proceso2_corto_subprocess_states_proceso1_corto_job_id'))

    op.drop_table('proceso2_corto_subprocess_states')
    op.drop_table('proceso2_corto_jobs')
    # ### end Alembic commands ###
