"""add proceso3 tables

Revision ID: 79d947b8b59e
Revises: 8c0a49504235
Create Date: 2026-02-16 20:26:49.692055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d947b8b59e'
down_revision = '8c0a49504235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso3_jobs',
    sa.Column('proceso1_job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proceso1_job_id'], ['proceso1_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proceso1_job_id')
    )
    op.create_table('proceso3_subprocess_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso1_job_id', sa.Integer(), nullable=False),
    sa.Column('subprocess_key', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proceso1_job_id'], ['proceso1_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proceso1_job_id', 'subprocess_key', name='uq_proceso3_job_subprocess_key')
    )
    with op.batch_alter_table('proceso3_subprocess_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proceso3_subprocess_states_proceso1_job_id'), ['proceso1_job_id'], unique=False)

    # NOTE: Do not drop Alembic's default version table. This backend uses
    # 'alembic_version_scienceluxe_backend' as configured in aplicacion/__init__.py.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso3_subprocess_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proceso3_subprocess_states_proceso1_job_id'))

    op.drop_table('proceso3_subprocess_states')
    op.drop_table('proceso3_jobs')
    # ### end Alembic commands ###
