"""add transition_sound to proceso4_scene_media

Revision ID: 9b559f97e1d0
Revises: e0b36953a274
Create Date: 2026-03-16 21:31:05.762414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b559f97e1d0'
down_revision = 'e0b36953a274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso4_scene_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition_sound', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso4_scene_media', schema=None) as batch_op:
        batch_op.drop_column('transition_sound')

    # ### end Alembic commands ###
