"""add section_tracks and reverb_config

Revision ID: a3990a644f1f
Revises: b2c3d4e5f6a7
Create Date: 2026-03-05 09:45:11.434083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3990a644f1f'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proceso4_reverb_config',
    sa.Column('proceso1_job_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('in_gain', sa.Float(), nullable=False),
    sa.Column('out_gain', sa.Float(), nullable=False),
    sa.Column('delay_ms', sa.Float(), nullable=False),
    sa.Column('decay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proceso1_job_id'], ['proceso1_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proceso1_job_id')
    )
    op.create_table('proceso4_section_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso1_job_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('pista_filename', sa.String(length=500), nullable=False),
    sa.Column('pista_path', sa.String(length=500), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('fade_in', sa.Float(), nullable=False),
    sa.Column('fade_out', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proceso1_job_id'], ['proceso1_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proceso1_job_id', 'section', name='uq_p4_section_track')
    )
    with op.batch_alter_table('proceso4_section_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proceso4_section_tracks_proceso1_job_id'), ['proceso1_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso4_section_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proceso4_section_tracks_proceso1_job_id'))

    op.drop_table('proceso4_section_tracks')
    op.drop_table('proceso4_reverb_config')
    # ### end Alembic commands ###
